### ISSUE TITLE
Store output in a different repository

### ISSUE THREAD

**Issue by fgiloux** [operator-framework/audit#46]
It may be advantageous to have the output of the audit-tool stored in a different repository:
- this would keep the code repository smaller
- this may avoid a few unnecessary rebases when reports get stored
- this would make things cleaner/simpler when CI automation is added
-
The index generation currently assumes that the report files are in a specific place in the directory structure of this repository. It could also be made configurable

**Comment by camilamacedo86** [comment]
Hi @fgiloux, 

Thank you for your feedback. In the medium/long term we might move the reports to a dedicated server. Ditto, so I'd not recommend we do changes before we check it. 

If we only do what you are suggesting here we will change the link/page path and then we will probably need to do that again sooner. 

After we check where/how/when we would like to put audit then we can re-use the hack scripts to be executed accordingly. Note that they are not commands from the tool but only scripts that have the purpose to execute a bunch/set of operations to generate the testdata. However, yes we can make that configurable as you suggested by using COBRA and flags in the same way that we implemented that for the tool. You can see in the SDK an example over that: https://github.com/operator-framework/operator-sdk/blob/master/hack/generate/samples/generate_testdata.go#L35-L45

**Comment by camilamacedo86** [comment]
I think we can be closed @fgiloux.
We are now only storing the dashboards that are used in the HTML page

So, I am closing this one. However, please, feel free to re-open if you need.
